<?php $APPLICATION->IncludeComponent(
    "bitrix:catalog.element",
    "",
    array(
        "ACTION_VARIABLE" => $arParams["ACTION_VARIABLE"],
        "ADD_DETAIL_TO_SLIDER" => $arParams["DETAIL_ADD_DETAIL_TO_SLIDER"],
        "ADD_ELEMENT_CHAIN" => "Y",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "ADD_SECTIONS_CHAIN" => $arParams['ADD_SECTIONS_CHAIN'],
        "ADD_TO_BASKET_ACTION" => array(
            0 => "BUY",
        ),
        "BACKGROUND_IMAGE" => "-",
        "BASKET_URL" => $arParams["BASKET_URL"],
        "BRAND_USE" => "N",
        "BROWSER_TITLE" => "-",
        "CACHE_GROUPS" => $arParams["CACHE_GROUPS"],
        "CACHE_TIME" => $arParams["CACHE_TIME"],
        "CACHE_TYPE" => $arParams["CACHE_TYPE"],
        "CHECK_SECTION_ID_VARIABLE" => "N",
        "COMPATIBLE_MODE" => "Y",
        "CONVERT_CURRENCY" => "N",
        "DETAIL_PICTURE_MODE" => $arParams["DETAIL_DETAIL_PICTURE_MODE"],
            'DETAIL_URL' => $arResult['FOLDER'].$arResult['URL_TEMPLATES']['element'],
        "DISABLE_INIT_JS_IN_COMPONENT" => "N",
        "DISPLAY_COMPARE" => "N",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PREVIEW_TEXT_MODE" => "E",
            'ELEMENT_ID' => $arResult['VARIABLES']['ELEMENT_ID'],
            'ELEMENT_CODE' => $arResult['VARIABLES']['ELEMENT_CODE'],
        "HIDE_NOT_AVAILABLE_OFFERS" => $arParams["HIDE_NOT_AVAILABLE_OFFERS"],
        "IBLOCK_ID" => $arParams["IBLOCK_ID"],
        "IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
        "IMAGE_RESOLUTION" => "16by9",
        "LINK_ELEMENTS_URL" => $arParams["LINK_ELEMENTS_URL"],
        "LINK_IBLOCK_ID" => "",
        "LINK_IBLOCK_TYPE" => "",
        "LINK_PROPERTY_SID" => "",
        "MESSAGE_404" => "",
        "MESS_BTN_ADD_TO_BASKET" => $arParams["MESS_BTN_ADD_TO_BASKET"],
        "MESS_BTN_BUY" => $arParams["MESS_BTN_BUY"],
        "MESS_BTN_SUBSCRIBE" => "Подписаться",
        "MESS_COMMENTS_TAB" => "Комментарии",
        "MESS_DESCRIPTION_TAB" => "Описание",
        "MESS_NOT_AVAILABLE" => $arParams["MESS_NOT_AVAILABLE"],
        "MESS_PRICE_RANGES_TITLE" => $arParams["MESS_PRICE_RANGES_TITLE"],
        "MESS_PROPERTIES_TAB" => $arParams["MESS_PROPERTIES_TAB"],
        "META_DESCRIPTION" => "-",
        "META_KEYWORDS" => "-",
        "OFFERS_LIMIT" => "0",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRICE_CODE" => $arParams["PRICE_CODE"],
        "PRICE_VAT_INCLUDE" => $arParams["PRICE_VAT_INCLUDE"],
        "PRICE_VAT_SHOW_VALUE" => $arParams["PRICE_VAT_SHOW_VALUE"],
        "PRODUCT_ID_VARIABLE" => $arParams["PRODUCT_ID_VARIABLE"],
        "PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
        "PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
        "PRODUCT_PROPERTIES" => array(
        ),
        "PRODUCT_PROPS_VARIABLE" => $arParams["PRODUCT_PROPS_VARIABLE"],
        "PRODUCT_QUANTITY_VARIABLE" => $arParams["PRODUCT_QUANTITY_VARIABLE"],
        "PRODUCT_SUBSCRIPTION" => "Y",
        "PROPERTY_CODE" => $arParams["DETAIL_PROPERTY_CODE"],
            'SECTION_CODE' => $arResult['VARIABLES']['SECTION_CODE'],
            'SECTION_ID' => $arResult['VARIABLES']['SECTION_ID'],
        "SECTION_ID_VARIABLE" => $arParams["SECTION_ID_VARIABLE"],
            'SECTION_URL' => $arResult['FOLDER'].$arResult['URL_TEMPLATES']['section'],
        "SEF_MODE" => $arParams["SEF_MODE"],
        "SET_BROWSER_TITLE" => $arParams["SET_BROWSER_TITLE"],
        "SET_CANONICAL_URL" => "N",
        "SET_LAST_MODIFIED" => $arParams["SET_LAST_MODIFIED"],
        "SET_META_DESCRIPTION" => "Y",
        "SET_META_KEYWORDS" => "Y",
        "SET_STATUS_404" => $arParams["SET_STATUS_404"],
        "SET_TITLE" => $arParams["SET_TITLE"],
        "SET_VIEWED_IN_COMPONENT" => "N",
        "SHOW_404" => $arParams["SHOW_404"],
        "SHOW_CLOSE_POPUP" => "N",
        "SHOW_DEACTIVATED" => $arParams["SHOW_DEACTIVATED"],
        "SHOW_DISCOUNT_PERCENT" => "N",
        "SHOW_MAX_QUANTITY" => $arParams["SHOW_MAX_QUANTITY"],
        "SHOW_OLD_PRICE" => $arParams["SHOW_OLD_PRICE"],
        "SHOW_PRICE_COUNT" => $arParams["SHOW_PRICE_COUNT"],
        "SHOW_SLIDER" => "N",
        "STRICT_SECTION_CHECK" => "N",
        "TEMPLATE_THEME" => $arParams["TEMPLATE_THEME"],
        "USE_COMMENTS" => "N",
        "USE_ELEMENT_COUNTER" => $arParams["USE_ELEMENT_COUNTER"],
        "USE_ENHANCED_ECOMMERCE" => $arParams["USE_ENHANCED_ECOMMERCE"],
        "USE_GIFTS_DETAIL" => $arParams["USE_GIFTS_DETAIL"],
        "USE_GIFTS_MAIN_PR_SECTION_LIST" => $arParams["USE_GIFTS_MAIN_PR_SECTION_LIST"],
        "USE_MAIN_ELEMENT_SECTION" => $arParams["USE_MAIN_ELEMENT_SECTION"],
        "USE_PRICE_COUNT" => $arParams["USE_PRICE_COUNT"],
        "USE_PRODUCT_QUANTITY" => $arParams["USE_PRODUCT_QUANTITY"],
        "USE_RATIO_IN_RANGES" => "Y",
        "USE_VOTE_RATING" => "N",
        "COMPONENT_TEMPLATE" => $arParams["COMPONENT_TEMPLATE"],
        "ADD_TO_BASKET_ACTION_PRIMARY" => array(
            0 => "BUY",
        )
    ),
    $component
);
